### ISSUE TITLE
Rating graph y axis only displays 00.00 if rating is too high

### ISSUE THREAD

**Issue by Gyoo** [zkrising/Tachi#1185]
Seen on DDR profiles : Flare Skill will easily go to 5 numbers and the ratings graph doesn't display correct values on the Y axis.

Example :
![image-6.png](https://github.com/user-attachments/assets/676174f3-d77f-4a2a-89cc-26e5eec36dc5)

**Comment by beer-psi** [comment]
Also affects maimai DX.

![Image of a maimai DX naive rating graph, where the Y axis is the rating. The Y axis only displays the two trailing digits.](https://nazunacord.net/xsXFeUugk7KO.png)
